version: "3.9"

services:
  transportation_service_db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  nextjs:
    build:
      context: ./orchestra/
      dockerfile: Dockerfile
    container_name: nextjs_app
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
