version: "3.9"

services:
  auth_server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    command: go run main.go -b 0.0.0.0
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
    env_file:
      - .env
    ports:
      - 5431:5431
